### PR TITLE
If not relevant, bypass quad and go to hypnos

### PR DESCRIPTION
**Pull request by jimr**
Previously, the pipeline would have stopped at this point, but passing
the article on through to the remainder of the pipeline still has some
value and at least leaves us with an indication that the pipeline
successfully completed without error, which we don't get if we stop half
way through.

### CODE REVIEW

**Comment by jimr** [comment]
I just resolved the merge conflict that showed up after you merged the other PRs. Happy to discuss this one - I realise it might be potentially controversial.

**Comment by vandurme** [comment]
This is a fine idea

**Comment by jimr** [comment]
Ace, thanks for all the merges!

**Comment by vandurme** [comment]
thanks for the requests

**Pull request merged**
